create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 12),
  device_id_hash text not null,
  score integer not null check (score >= 0 and score <= 99999999),
  best_combo integer not null default 0 check (best_combo >= 0),
  made integer not null default 0 check (made >= 0),
  served integer not null default 0 check (served >= 0),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

create index if not exists scores_rank_idx
  on public.scores (score desc, best_combo desc, served desc, created_at desc);

create index if not exists scores_device_idx
  on public.scores (device_id_hash, created_at desc);

